disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - weak_delegate
  - explicit_enum_raw_value
identifier_name:
  min_length:
    warning: 2
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - wooptest/ThirdParty
nesting:
  type_level: 3
